language: node_js

os:
  - linux

before_script:
  - echo "deb http://archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe" | sudo tee /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install shellcheck
  - sudo pip install flake8
  - sudo pip install pep8
  - npm install -g jsonlint

script:
 - jsonlint cloudbuilder/parameters.json
 - jsonlint cloudbuilder/template.json
 - shellcheck -e SC2034,SC2139 cloudbuilder/*.sh
 - flake8 */deploy.py
 - pep8 */deploy.py
